line-length = 120
target-version = "py310"

# Temporary suppression to unblock `fix-waveform-port-integration`.
# Technical debt is tracked in OpenSpec change `cleanup-ruff-violations`.

[lint]
select = ["E", "F", "I", "N", "UP", "B", "C4", "SIM"]
ignore = ["E501"]
exclude = [
    ".venv",
    "__pycache__",
    "build",
    "dist",
    "ui/*",
    "services/*",
    "scripts/*",
    "tests/*",
    "app.py",
    "audio_utils.py",
    "config.py",
    "waveform_viewer.py",
    "pdf_viewer.py",
    "settings_page.py",
    # Temporary legacy suppressions (see cleanup-ruff-violations)
    "adapters/ai/vlm.py",
    "adapters/audio/ai_helpers.py",
    "adapters/audio/ai_mode_detector.py",
    "adapters/audio/chained_detector.py",
    "adapters/audio/steps.py",
    "adapters/audio/wav_reader.py",
    "adapters/pdf/renderer.py",
    "core/domain/parsing.py",
    "core/domain/steps.py",
    "pdf_extractor.py",
    "openspec/changes/*",
    "openspec/specs/*",
    "openspec/archive/*",
]

[lint.per-file-ignores]
"tests/test_characterization.py" = ["F401"]
