# This file was automatically generated by build_resources.py
# Qt resource module (minimal fallback)
from PyQt6.QtCore import qRegisterResourceData, qUnregisterResourceData

# Note: QResource.addSearchPath is not for resource files compiled by pyrcc6,
# and directly accessing QResource.addSearchPath does not function as intended
# for :/ paths. The proper mechanism involves data registered by pyrcc6.
# When pyrcc6 is absent, we rely on ui/theme.py's direct file loading logic.


def qInitResources():
    """Initialize resources (called on module import)"""
    pass


def qCleanupResources():
    """Cleanup resources"""
    pass


# Auto-initialize on import
qInitResources()
